name: Code Quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: node_cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.node_cache.outputs.cache-hit != 'true'
      - run: yarn install --frozen-lockfile
      - run: yarn ci
